// Code generated by protoc-gen-go.
// source: visitor.proto
// DO NOT EDIT!

/*
Package visitor is a generated protocol buffer package.

It is generated from these files:
	visitor.proto

It has these top-level messages:
	Record
	Visitor
*/
package visitor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Hid  int32 `protobuf:"varint,1,opt,name=Hid,json=hid" json:"Hid,omitempty"`
	Vid  int32 `protobuf:"varint,2,opt,name=Vid,json=vid" json:"Vid,omitempty"`
	Time int32 `protobuf:"varint,3,opt,name=Time,json=time" json:"Time,omitempty"`
	Flag int32 `protobuf:"varint,4,opt,name=Flag,json=flag" json:"Flag,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Visitor struct {
	Records []*Record `protobuf:"bytes,1,rep,name=Records,json=records" json:"Records,omitempty"`
}

func (m *Visitor) Reset()                    { *m = Visitor{} }
func (m *Visitor) String() string            { return proto.CompactTextString(m) }
func (*Visitor) ProtoMessage()               {}
func (*Visitor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Visitor) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "visitor.Record")
	proto.RegisterType((*Visitor)(nil), "visitor.Visitor")
}

func init() { proto.RegisterFile("visitor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xcb, 0x2c, 0xce,
	0x2c, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x42, 0xb8,
	0xd8, 0x82, 0x52, 0x93, 0xf3, 0x8b, 0x52, 0x84, 0x04, 0xb8, 0x98, 0x3d, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x33, 0x32, 0xc1, 0x22, 0x61, 0x99, 0x29, 0x12, 0x4c, 0x10,
	0x91, 0xb2, 0xcc, 0x14, 0x21, 0x21, 0x2e, 0x96, 0x90, 0xcc, 0xdc, 0x54, 0x09, 0x66, 0xb0, 0x10,
	0x4b, 0x49, 0x66, 0x6e, 0x2a, 0x48, 0xcc, 0x2d, 0x27, 0x31, 0x5d, 0x82, 0x05, 0x22, 0x96, 0x96,
	0x93, 0x98, 0xae, 0x64, 0xc2, 0xc5, 0x1e, 0x06, 0xb1, 0x40, 0x48, 0x93, 0x8b, 0x1d, 0x62, 0x41,
	0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0xbf, 0x1e, 0xcc, 0x29, 0x10, 0xf1, 0x20, 0xf6,
	0x22, 0x88, 0x7c, 0x12, 0x1b, 0xd8, 0x6d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x40,
	0x37, 0xa3, 0xac, 0x00, 0x00, 0x00,
}
